### ISSUE TITLE
Nigel owner of wordpane.com / WPCLOUDDEPLOY no more :(

### ISSUE THREAD

**Issue by ghost** [osidney/scripts-openlitespeed#1]
https://www.herdegenfuneralhome.com/obituaries/Nigel-Rasheed-Bahadur?obId=31617195

What happens now --- wordpane.com was all based on wpclouddeploy.com :(((((((

**Comment by osidney** [comment]
Wow, I didn't know that. I haven't used wpclouddeploy for over a year, so I'm very surprised by this, I hope the project can continue in some way.

**Comment by ghost** [comment]
> Wow, I didn't know that. I haven't used wpclouddeploy for over a year, so I'm very surprised by this, I hope the project can continue in some way.

Oh well but isint wordpane heavily using WPCD as its backbone. It quite evident when we used your test server. Lets see how the project revives.

**Comment by osidney** [comment]
WordPane hasn't used wpclouddeploy for years in our system, we've been out of wpccloudeploy for about two years now, we don't know how the project is going anymore, I've heard from other members about this, we hope the project will continue with a developer, but today it is not part of the scope of our company.
